CORE-3223 Removed transfer-encoding from fwd-request headers.
Donkey was throwing the following exception for some requests forwarded to metadactyl:
org.apache.http.ProtocolException: Transfer-encoding header already present

This caused some requests from Tito, routed initially through zoidberg, to fail; such as preview-template and update-template.